package com.piaget.pojo;
// Generated Nov 18, 2018 2:42:44 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Alumnos generated by hbm2java
 */
public class Alumnos  implements java.io.Serializable {


     private String idalumno;
     private Anos anos;
     private Apoderados apoderados;
     private Comunas comunas;
     private Short nummatricula;
     private Integer runalumno;
     private Character digitoal;
     private String nomalumno;
     private String paternoalu;
     private String maternoalu;
     private Date fnacimiento;
     private Integer fono;
     private String sexo;
     private String direccion;
     private String nivelEduPadre;
     private String nivelEduMadre;
     private Matricula matricula;

    public Alumnos() {
    }

	
    public Alumnos(String idalumno, Anos anos) {
        this.idalumno = idalumno;
        this.anos = anos;
    }
    public Alumnos(String idalumno, Anos anos, Apoderados apoderados, Comunas comunas, Short nummatricula, Integer runalumno, Character digitoal, String nomalumno, String paternoalu, String maternoalu, Date fnacimiento, Integer fono, String sexo, String direccion, String nivelEduPadre, String nivelEduMadre, Matricula matricula) {
       this.idalumno = idalumno;
       this.anos = anos;
       this.apoderados = apoderados;
       this.comunas = comunas;
       this.nummatricula = nummatricula;
       this.runalumno = runalumno;
       this.digitoal = digitoal;
       this.nomalumno = nomalumno;
       this.paternoalu = paternoalu;
       this.maternoalu = maternoalu;
       this.fnacimiento = fnacimiento;
       this.fono = fono;
       this.sexo = sexo;
       this.direccion = direccion;
       this.nivelEduPadre = nivelEduPadre;
       this.nivelEduMadre = nivelEduMadre;
       this.matricula = matricula;
    }
   
    public String getIdalumno() {
        return this.idalumno;
    }
    
    public void setIdalumno(String idalumno) {
        this.idalumno = idalumno;
    }
    public Anos getAnos() {
        return this.anos;
    }
    
    public void setAnos(Anos anos) {
        this.anos = anos;
    }
    public Apoderados getApoderados() {
        return this.apoderados;
    }
    
    public void setApoderados(Apoderados apoderados) {
        this.apoderados = apoderados;
    }
    public Comunas getComunas() {
        return this.comunas;
    }
    
    public void setComunas(Comunas comunas) {
        this.comunas = comunas;
    }
    public Short getNummatricula() {
        return this.nummatricula;
    }
    
    public void setNummatricula(Short nummatricula) {
        this.nummatricula = nummatricula;
    }
    public Integer getRunalumno() {
        return this.runalumno;
    }
    
    public void setRunalumno(Integer runalumno) {
        this.runalumno = runalumno;
    }
    public Character getDigitoal() {
        return this.digitoal;
    }
    
    public void setDigitoal(Character digitoal) {
        this.digitoal = digitoal;
    }
    public String getNomalumno() {
        return this.nomalumno;
    }
    
    public void setNomalumno(String nomalumno) {
        this.nomalumno = nomalumno;
    }
    public String getPaternoalu() {
        return this.paternoalu;
    }
    
    public void setPaternoalu(String paternoalu) {
        this.paternoalu = paternoalu;
    }
    public String getMaternoalu() {
        return this.maternoalu;
    }
    
    public void setMaternoalu(String maternoalu) {
        this.maternoalu = maternoalu;
    }
    public Date getFnacimiento() {
        return this.fnacimiento;
    }
    
    public void setFnacimiento(Date fnacimiento) {
        this.fnacimiento = fnacimiento;
    }
    public Integer getFono() {
        return this.fono;
    }
    
    public void setFono(Integer fono) {
        this.fono = fono;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getNivelEduPadre() {
        return this.nivelEduPadre;
    }
    
    public void setNivelEduPadre(String nivelEduPadre) {
        this.nivelEduPadre = nivelEduPadre;
    }
    public String getNivelEduMadre() {
        return this.nivelEduMadre;
    }
    
    public void setNivelEduMadre(String nivelEduMadre) {
        this.nivelEduMadre = nivelEduMadre;
    }
    public Matricula getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(Matricula matricula) {
        this.matricula = matricula;
    }

}


