package com.piaget.pojo;
// Generated Sep 26, 2018 5:23:27 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Anos generated by hbm2java
 */
public class Anos  implements java.io.Serializable {


     private Short idAno;
     private int ano;
     private Date finicio;
     private Date ftermino;
     private String situacion;
     private String regimen;
     private Set matriculas = new HashSet(0);
     private Set apoderadoses = new HashSet(0);
     private Set usuarioses = new HashSet(0);
     private Set cursoses = new HashSet(0);
     private Set alumnoses = new HashSet(0);

    public Anos() {
    }

	
    public Anos(int ano) {
        this.ano = ano;
    }
    public Anos(int ano, Date finicio, Date ftermino, String situacion, String regimen, Set matriculas, Set apoderadoses, Set usuarioses, Set cursoses, Set alumnoses) {
       this.ano = ano;
       this.finicio = finicio;
       this.ftermino = ftermino;
       this.situacion = situacion;
       this.regimen = regimen;
       this.matriculas = matriculas;
       this.apoderadoses = apoderadoses;
       this.usuarioses = usuarioses;
       this.cursoses = cursoses;
       this.alumnoses = alumnoses;
    }
   
    public Short getIdAno() {
        return this.idAno;
    }
    
    public void setIdAno(Short idAno) {
        this.idAno = idAno;
    }
    public int getAno() {
        return this.ano;
    }
    
    public void setAno(int ano) {
        this.ano = ano;
    }
    public Date getFinicio() {
        return this.finicio;
    }
    
    public void setFinicio(Date finicio) {
        this.finicio = finicio;
    }
    public Date getFtermino() {
        return this.ftermino;
    }
    
    public void setFtermino(Date ftermino) {
        this.ftermino = ftermino;
    }
    public String getSituacion() {
        return this.situacion;
    }
    
    public void setSituacion(String situacion) {
        this.situacion = situacion;
    }
    public String getRegimen() {
        return this.regimen;
    }
    
    public void setRegimen(String regimen) {
        this.regimen = regimen;
    }
    public Set getMatriculas() {
        return this.matriculas;
    }
    
    public void setMatriculas(Set matriculas) {
        this.matriculas = matriculas;
    }
    public Set getApoderadoses() {
        return this.apoderadoses;
    }
    
    public void setApoderadoses(Set apoderadoses) {
        this.apoderadoses = apoderadoses;
    }
    public Set getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }
    public Set getCursoses() {
        return this.cursoses;
    }
    
    public void setCursoses(Set cursoses) {
        this.cursoses = cursoses;
    }
    public Set getAlumnoses() {
        return this.alumnoses;
    }
    
    public void setAlumnoses(Set alumnoses) {
        this.alumnoses = alumnoses;
    }
}


