package com.piaget.pojo;
// Generated Nov 18, 2018 2:42:44 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Colegio generated by hbm2java
 */
public class Colegio  implements java.io.Serializable {


     private String rbd;
     private Comunas comunas;
     private String run;
     private String establecimiento;
     private Short numresol;
     private Date dateresol;
     private Character letra;
     private Short numero;
     private String dependencia;
     private Integer fono;
     private String email;
     private String tipo;
     private String tipeducacion;
     private String idioma;
     private String sexo;
     private String metodo;
     private String formacion;
     private String area;
     private String direccion;
     private String web;

    public Colegio() {
    }

	
    public Colegio(String rbd) {
        this.rbd = rbd;
    }
    public Colegio(String rbd, Comunas comunas, String run, String establecimiento, Short numresol, Date dateresol, Character letra, Short numero, String dependencia, Integer fono, String email, String tipo, String tipeducacion, String idioma, String sexo, String metodo, String formacion, String area, String direccion, String web) {
       this.rbd = rbd;
       this.comunas = comunas;
       this.run = run;
       this.establecimiento = establecimiento;
       this.numresol = numresol;
       this.dateresol = dateresol;
       this.letra = letra;
       this.numero = numero;
       this.dependencia = dependencia;
       this.fono = fono;
       this.email = email;
       this.tipo = tipo;
       this.tipeducacion = tipeducacion;
       this.idioma = idioma;
       this.sexo = sexo;
       this.metodo = metodo;
       this.formacion = formacion;
       this.area = area;
       this.direccion = direccion;
       this.web = web;
    }
   
    public String getRbd() {
        return this.rbd;
    }
    
    public void setRbd(String rbd) {
        this.rbd = rbd;
    }
    public Comunas getComunas() {
        return this.comunas;
    }
    
    public void setComunas(Comunas comunas) {
        this.comunas = comunas;
    }
    public String getRun() {
        return this.run;
    }
    
    public void setRun(String run) {
        this.run = run;
    }
    public String getEstablecimiento() {
        return this.establecimiento;
    }
    
    public void setEstablecimiento(String establecimiento) {
        this.establecimiento = establecimiento;
    }
    public Short getNumresol() {
        return this.numresol;
    }
    
    public void setNumresol(Short numresol) {
        this.numresol = numresol;
    }
    public Date getDateresol() {
        return this.dateresol;
    }
    
    public void setDateresol(Date dateresol) {
        this.dateresol = dateresol;
    }
    public Character getLetra() {
        return this.letra;
    }
    
    public void setLetra(Character letra) {
        this.letra = letra;
    }
    public Short getNumero() {
        return this.numero;
    }
    
    public void setNumero(Short numero) {
        this.numero = numero;
    }
    public String getDependencia() {
        return this.dependencia;
    }
    
    public void setDependencia(String dependencia) {
        this.dependencia = dependencia;
    }
    public Integer getFono() {
        return this.fono;
    }
    
    public void setFono(Integer fono) {
        this.fono = fono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getTipeducacion() {
        return this.tipeducacion;
    }
    
    public void setTipeducacion(String tipeducacion) {
        this.tipeducacion = tipeducacion;
    }
    public String getIdioma() {
        return this.idioma;
    }
    
    public void setIdioma(String idioma) {
        this.idioma = idioma;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getMetodo() {
        return this.metodo;
    }
    
    public void setMetodo(String metodo) {
        this.metodo = metodo;
    }
    public String getFormacion() {
        return this.formacion;
    }
    
    public void setFormacion(String formacion) {
        this.formacion = formacion;
    }
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getWeb() {
        return this.web;
    }
    
    public void setWeb(String web) {
        this.web = web;
    }




}


