package com.piaget.pojo;
// Generated Dec 10, 2018 9:29:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Comunas generated by hbm2java
 */
public class Comunas  implements java.io.Serializable {


     private Short codcomuna;
     private Provincias provincias;
     private String comuna;
     private Set alumnoses = new HashSet(0);
     private Set sedeses = new HashSet(0);
     private Set colegios = new HashSet(0);

    public Comunas() {
    }

	
    public Comunas(String comuna) {
        this.comuna = comuna;
    }
    public Comunas(Provincias provincias, String comuna, Set alumnoses, Set sedeses, Set colegios) {
       this.provincias = provincias;
       this.comuna = comuna;
       this.alumnoses = alumnoses;
       this.sedeses = sedeses;
       this.colegios = colegios;
    }
   
    public Short getCodcomuna() {
        return this.codcomuna;
    }
    
    public void setCodcomuna(Short codcomuna) {
        this.codcomuna = codcomuna;
    }
    public Provincias getProvincias() {
        return this.provincias;
    }
    
    public void setProvincias(Provincias provincias) {
        this.provincias = provincias;
    }
    public String getComuna() {
        return this.comuna;
    }
    
    public void setComuna(String comuna) {
        this.comuna = comuna;
    }
    public Set getAlumnoses() {
        return this.alumnoses;
    }
    
    public void setAlumnoses(Set alumnoses) {
        this.alumnoses = alumnoses;
    }
    public Set getSedeses() {
        return this.sedeses;
    }
    
    public void setSedeses(Set sedeses) {
        this.sedeses = sedeses;
    }
    public Set getColegios() {
        return this.colegios;
    }
    
    public void setColegios(Set colegios) {
        this.colegios = colegios;
    }




}


