package com.piaget.pojo;
// Generated Sep 26, 2018 5:23:27 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Profiles generated by hbm2java
 */
public class Profiles  implements java.io.Serializable {


     private Short idProfile;
     private String tipo;
     private Set profesoreses = new HashSet(0);

    public Profiles() {
    }

	
    public Profiles(String tipo) {
        this.tipo = tipo;
    }
    public Profiles(String tipo, Set profesoreses) {
       this.tipo = tipo;
       this.profesoreses = profesoreses;
    }
   
    public Short getIdProfile() {
        return this.idProfile;
    }
    
    public void setIdProfile(Short idProfile) {
        this.idProfile = idProfile;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getProfesoreses() {
        return this.profesoreses;
    }
    
    public void setProfesoreses(Set profesoreses) {
        this.profesoreses = profesoreses;
    }

}


