package com.piaget.pojo;
// Generated Sep 26, 2018 5:23:27 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Profesores generated by hbm2java
 */
public class Profesores  implements java.io.Serializable {


     private String idProfe;
     private Profiles profiles;
     private String runProfe;
     private String nomProfe;
     private String paterProfe;
     private String materProfe;
     private Integer fonoProfe;
     private String addressProfe;
     private String emailProfe;
     private Set cursoses = new HashSet(0);
     private Set usuarioses = new HashSet(0);

    public Profesores() {
    }

	
    public Profesores(String idProfe, Profiles profiles, String runProfe, String nomProfe, String paterProfe, String materProfe, String emailProfe) {
        this.idProfe = idProfe;
        this.profiles = profiles;
        this.runProfe = runProfe;
        this.nomProfe = nomProfe;
        this.paterProfe = paterProfe;
        this.materProfe = materProfe;
        this.emailProfe = emailProfe;
    }
    public Profesores(String idProfe, Profiles profiles, String runProfe, String nomProfe, String paterProfe, String materProfe, Integer fonoProfe, String addressProfe, String emailProfe, Set cursoses, Set usuarioses) {
       this.idProfe = idProfe;
       this.profiles = profiles;
       this.runProfe = runProfe;
       this.nomProfe = nomProfe;
       this.paterProfe = paterProfe;
       this.materProfe = materProfe;
       this.fonoProfe = fonoProfe;
       this.addressProfe = addressProfe;
       this.emailProfe = emailProfe;
       this.cursoses = cursoses;
       this.usuarioses = usuarioses;
    }
   
    public String getIdProfe() {
        return this.idProfe;
    }
    
    public void setIdProfe(String idProfe) {
        this.idProfe = idProfe;
    }
    public Profiles getProfiles() {
        return this.profiles;
    }
    
    public void setProfiles(Profiles profiles) {
        this.profiles = profiles;
    }
    public String getRunProfe() {
        return this.runProfe;
    }
    
    public void setRunProfe(String runProfe) {
        this.runProfe = runProfe;
    }
    public String getNomProfe() {
        return this.nomProfe;
    }
    
    public void setNomProfe(String nomProfe) {
        this.nomProfe = nomProfe;
    }
    public String getPaterProfe() {
        return this.paterProfe;
    }
    
    public void setPaterProfe(String paterProfe) {
        this.paterProfe = paterProfe;
    }
    public String getMaterProfe() {
        return this.materProfe;
    }
    
    public void setMaterProfe(String materProfe) {
        this.materProfe = materProfe;
    }
    public Integer getFonoProfe() {
        return this.fonoProfe;
    }
    
    public void setFonoProfe(Integer fonoProfe) {
        this.fonoProfe = fonoProfe;
    }
    public String getAddressProfe() {
        return this.addressProfe;
    }
    
    public void setAddressProfe(String addressProfe) {
        this.addressProfe = addressProfe;
    }
    public String getEmailProfe() {
        return this.emailProfe;
    }
    
    public void setEmailProfe(String emailProfe) {
        this.emailProfe = emailProfe;
    }
    public Set getCursoses() {
        return this.cursoses;
    }
    
    public void setCursoses(Set cursoses) {
        this.cursoses = cursoses;
    }
    public Set getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }




}


