package com.piaget.pojo;
// Generated Nov 18, 2018 2:42:44 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Provincias generated by hbm2java
 */
public class Provincias  implements java.io.Serializable {


     private Short idprovincia;
     private Regiones regiones;
     private String provincia;
     private Set comunases = new HashSet(0);

    public Provincias() {
    }

    public Provincias(Regiones regiones, String provincia, Set comunases) {
       this.regiones = regiones;
       this.provincia = provincia;
       this.comunases = comunases;
    }
   
    public Short getIdprovincia() {
        return this.idprovincia;
    }
    
    public void setIdprovincia(Short idprovincia) {
        this.idprovincia = idprovincia;
    }
    public Regiones getRegiones() {
        return this.regiones;
    }
    
    public void setRegiones(Regiones regiones) {
        this.regiones = regiones;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public Set getComunases() {
        return this.comunases;
    }
    
    public void setComunases(Set comunases) {
        this.comunases = comunases;
    }




}


