package com.piaget.pojo;
// Generated Nov 18, 2018 2:42:44 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sedes generated by hbm2java
 */
public class Sedes  implements java.io.Serializable {


     private Short idsede;
     private Comunas comunas;
     private String namesede;
     private String direccion;
     private Set cursoses = new HashSet(0);

    public Sedes() {
    }

    public Sedes(Comunas comunas, String namesede, String direccion, Set cursoses) {
       this.comunas = comunas;
       this.namesede = namesede;
       this.direccion = direccion;
       this.cursoses = cursoses;
    }
   
    public Short getIdsede() {
        return this.idsede;
    }
    
    public void setIdsede(Short idsede) {
        this.idsede = idsede;
    }
    public Comunas getComunas() {
        return this.comunas;
    }
    
    public void setComunas(Comunas comunas) {
        this.comunas = comunas;
    }
    public String getNamesede() {
        return this.namesede;
    }
    
    public void setNamesede(String namesede) {
        this.namesede = namesede;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set getCursoses() {
        return this.cursoses;
    }
    
    public void setCursoses(Set cursoses) {
        this.cursoses = cursoses;
    }




}


