package com.piaget.pojo;
// Generated Sep 26, 2018 5:23:27 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tensenanza generated by hbm2java
 */
public class Tensenanza  implements java.io.Serializable {


     private String idense;
     private Planes planes;
     private short idnum;
     private String namense;
     private Date dateresol;
     private Set cursoses = new HashSet(0);

    public Tensenanza() {
    }

	
    public Tensenanza(String idense, Planes planes, short idnum, String namense, Date dateresol) {
        this.idense = idense;
        this.planes = planes;
        this.idnum = idnum;
        this.namense = namense;
        this.dateresol = dateresol;
    }
    public Tensenanza(String idense, Planes planes, short idnum, String namense, Date dateresol, Set cursoses) {
       this.idense = idense;
       this.planes = planes;
       this.idnum = idnum;
       this.namense = namense;
       this.dateresol = dateresol;
       this.cursoses = cursoses;
    }
   
    public String getIdense() {
        return this.idense;
    }
    
    public void setIdense(String idense) {
        this.idense = idense;
    }
    public Planes getPlanes() {
        return this.planes;
    }
    
    public void setPlanes(Planes planes) {
        this.planes = planes;
    }
    public short getIdnum() {
        return this.idnum;
    }
    
    public void setIdnum(short idnum) {
        this.idnum = idnum;
    }
    public String getNamense() {
        return this.namense;
    }
    
    public void setNamense(String namense) {
        this.namense = namense;
    }
    public Date getDateresol() {
        return this.dateresol;
    }
    
    public void setDateresol(Date dateresol) {
        this.dateresol = dateresol;
    }
    public Set getCursoses() {
        return this.cursoses;
    }
    
    public void setCursoses(Set cursoses) {
        this.cursoses = cursoses;
    }




}


